---
- name: Install Apache package
  package:
    name: apache2
    state: present

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: Open port 80 in ufw
  ufw:
    rule: allow
    port: 80
    proto: tcp
    
- name: Configure index.html with system facts
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Check website availability
  uri:
    url: "http://{{ inventory_hostname }}"
    status_code: 200
    return_content: yes
    validate_certs: no
